[build]
  # Build the client and server bundles
  command = "npm run build"

  # Publish output directory for the frontend (Vite output)
  publish = "dist"

  # Directory containing Netlify Functions
  functions = "netlify/functions"
