# Netlify configuration for full-stack build
[build]
  command = "npm ci && npm run build"
  publish = "dist/public"

# Serve index.html for all client-side routes
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
  force  = false
