# Netlify configuration for client build and API/WebSocket proxy
[build]
  # Root of the frontend app
  base = "."
  # Directory where Vite outputs the production build
  publish = "dist/public"
  # Command to install deps and build
  command = "npm ci && npm run build"

[[redirects]]
  # Proxy all API calls to your backend (replace <YOUR_BACKEND_URL>)
  from = "/api/*"
  to = "https://<YOUR_BACKEND_URL>/:splat"
  status = 200
  force = true

[[redirects]]
  # Proxy WebSocket connections
  from = "/ws"
  to = "wss://<YOUR_BACKEND_URL>/ws"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
